<!-- Core -->
<script src="{{ argon("assets/vendor/jquery/dist/jquery.min.js") }}"></script>
<script src="{{ argon("assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js") }}"></script>
<script src="{{ argon("assets/vendor/js-cookie/js.cookie.js") }}"></script>
<script src="{{ argon("assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js") }}"></script>
<script src="{{ argon("assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js") }}"></script>
<!-- Optional JS -->
<script src="{{ argon("assets/vendor/moment/min/moment.min.js") }}"></script>
<script src="{{ argon("assets/vendor/fullcalendar/dist/fullcalendar.min.js") }}"></script>
<script src="{{ argon("assets/vendor/sweetalert2/dist/sweetalert2.min.js") }}"></script>
<script src="{{ argon("assets/vendor/jvectormap-next/jquery-jvectormap.min.js") }}"></script>
<script src="{{ argon("assets/js/vendor/jvectormap/jquery-jvectormap-world-mill.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net/js/jquery.dataTables.min.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net-buttons/js/buttons.html5.min.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net-buttons/js/buttons.flash.min.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net-buttons/js/buttons.print.min.js") }}"></script>
<script src="{{ argon("assets/vendor/datatables.net-select/js/dataTables.select.min.js") }}"></script>
<!-- Argon JS -->
<script src="{{ argon("assets/js/argon.js?v=1.1.0") }}"></script>
